name: 'Web Request Action'
description: 'Send Web Request'
inputs:
  url:
    description: 'Web request URL endpoint'
    required: true
  method:
    description: 'Web request method (`GET`, `POST`, `PUT`, `PATCH`)'
    required: true
    default: GET
  payload:
    description: Web request payload in JSON format
    required: false
  username:
    description: username for BASIC auth
    required: false
  password:
    description: password for BASIC auth
    required: false
outputs:
  time:
    description: 'Time of execution'
runs:
  using: 'node12'
  main: 'dist/index.js'
