on: [push]
env:
  MY_NAME: Satak the great
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: satak/hello-action@master
        with:
          payload: '{"name": "${{ env.MY_NAME }}"}'
          webhook-id: ${{ secrets.WEBHOOK_ID }}
      # Use the output from the `hello` step
      - name: Get the output time
        shell: pwsh
        run: |
          $output = '${{ steps.hello.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) statusCode $($output.statusCode)"
