on: [push]
env:
  MY_NAME: Satak the great
jobs:
  webhook_job:
    runs-on: ubuntu-latest
    name: Job to send payload to webhook API
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Webhook API request
        id: webhook
        uses: satak/hello-action@master
        with:
          payload: '{"name": "${{ env.MY_NAME }}"}'
          webhook-id: ${{ secrets.WEBHOOK_ID }}
      - name: Get the output
        shell: pwsh
        run: |
          $output = '${{ steps.webhook.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) statusCode $($output.statusCode)"
