on: [push]
env:
  WEBHOOK_ID: 8333e2d2-80bb-4bc2-924d-e2c007095181
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hello world action step
        id: hello
        uses: satak/hello-action@master
        with:
          who-to-greet: 'Satak the master'
          secret: ${{ secrets.MY_SECRET }}
          webhook-id: $WEBHOOK_ID
      # Use the output from the `hello` step
      - name: Get the output time
        shell: pwsh
        run: |
          $output = '${{ steps.hello.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) name $($output.name) statusCode $($output.statusCode)"
